data = {}
data[ 'phone' ] = business.local_phone
data[ 'phone_area' ] = business.local_phone.split("-")[0]
data[ 'phone_prefix' ] = business.local_phone.split("-")[1]
data[ 'phone_suffix' ] = business.local_phone.split("-")[2]
data[ 'email' ] = business.bings.first.email 
data[ 'password' ] = Yahoo.make_password
data[ 'business' ] = business.business_name
data[ 'address' ] = business.address + ' ' + business.address2
data[ 'city' ] = business.city
data[ 'state' ] = business.state 
data[ 'zip' ] = business.zip
data[ 'category' ] = business.category1
data[ 'sub_category' ] = business.category2
data[ 'first_name' ] = business.contact_first_name
data[ 'last_name' ] = business.contact_last_name
data[ 'website' ] = business.company_website
data[ 'payments' ] = Thinklocal.payment_methods(business) 
data
