data = {}
data[ '24hours' ]                = business.open_24_hours
data[ 'hours' ]                  = Cylex.get_hours(business)
data[ 'payments' ]               = Cylex.payment_methods(business)
data[ 'phone' ]                  = business.local_phone
data[ 'mobile' ]                 = business.mobile_phone
data[ 'fax' ]                    = business.fax_number
data[ 'username' ]               = business.bings.first.email.split("@")[0] + 9.to_s
data[ 'email' ]                  = business.bings.first.email 
data[ 'business' ]               = business.business_name
data[ 'search_business' ]        = business.business_name.downcase.gsub(/[^A-Z0-9']/i, '-')
data[ 'address' ]                = business.address
data[ 'address2' ]               = business.address2
data[ 'city' ]                   = business.city
data[ 'state' ]                  = business.state_name
data[ 'zip' ]                    = business.zip
data[ 'description' ]            = business.business_description
data[ 'keywords' ]               = business.keywords
data[ 'website' ]                = business.company_website
data[ 'name_title' ]             = business.contact_prefix
data[ 'first_name' ]             = business.contact_first_name
data[ 'last_name' ]              = business.contact_last_name
data[ 'password' ]               = Yahoo.make_password[0..13]
data[ 'gender' ]                 = business.contact_gender
data[ 'update_reason' ]          = 'Update'
data