data = {}
data[ 'phone' ] = 					business.local_phone
data[ 'keywords'] = 				business.keywords
data[ 'username' ] = 				business.bizzspots.first.username
data[ 'email' ] = 					business.bizzspots.first.email 
data[ 'business' ] = 				business.business_name
data[ 'address' ] = 				business.address + ' ' + business.address2
data[ 'city' ] = 					business.city
data[ 'state' ] = 					business.state 
data[ 'zip' ] = 					business.zip
data[ 'business_description'] = 	business.business_description
data[ 'website'] = 					business.company_website
data[ 'role' ] = 					'owner'
data[ 'name_title' ] = 				business.contact_prefix
data[ 'first_name' ] = 				business.contact_first_name
data[ 'last_name' ] = 				business.contact_last_name
data[ 'password' ] = 				business.bizzspots.first.password
data[ 'reason_for_info_update'] = 	''
data[ 'paymentTypes' ] 			= 	[ :masterCard, :cash, :check, :visa ]
data['category'] = 					business.category1
data['monday'] =					business.monday_open    + "-" +		business.monday_close
data['tuesday'] =					business.tuesday_open   + "-" + 	business.tuesday_close
data['wednesday'] =					business.wednesday_open + "-" + 	business.wednesday_close
data['thursday'] =					business.thursday_open  + "-" + 	business.thursday_close
data['friday'] =					business.friday_open 	+ "-" + 	business.friday_close
data