data = {}
seed = rand(10000).to_s()
data['fb_email'] 		= ''
data['fb_password'] 		= ''
data['fname'] 		= business.contact_first_name
data['lname'] 		= business.contact_last_name
data['display_name'] 		= data['fname'] + data['lname']  + seed
data['email'] 			= business.bings.first.email
data['password'] 		= Yahoo.make_password
data['recieve_offers'] 		= false
data['extra_fields'] 		= false
data['address'] 		= business.address + ' ' + business.address2
data['city'] 			= business.city
data['state'] 			= business.state_name
data['zip'] 		= business.zip
data['localphone']  = business.local_phone
data['business']    = business.business_name
data['gender'] 			= business.contact_gender
data['dob_d'] 			= business.contact_birthday.split("/")[0]
data['dob_m'] 			= business.contact_birthday.split("/")[1]
data['dob_y'] 			= business.contact_birthday.split("/")[2]
data['hide_birthday'] 		= true
data['mob_1'] 			= business.local_phone.split("-")[0]
data['mob_2'] 			= business.local_phone.split("-")[1]
data['mob_3'] 			= business.local_phone.split("-")[2]
data['category1']   = business.category1[0..5]
data['category2']   = business.category2[0..5]
data[ '24hours' ]		= business.open_24_hours
data[ 'hours' ]			= Localndex.get_hours( business )
data['description'] = business.business_description
data['services']    = business.category1 + ", " +business.category2 + ", " +business.category3
data['payments']    = Localcom.payment_methods(business)
data
