data = {}
data[ 'username' ]		= business.freebusinessdirectories.first.username
data[ 'password' ]		= business.bings.first.password
data[ 'description' ]		= business.business_description
data[ 'website' ]		= business.company_website
data[ 'salutation' ]		= business.contact_prefix
data[ 'middlename' ]		= business.contact_middle_name
data[ 'position' ]		= "Owner"
data[ 'areacode' ]		= business.local_phone.split("-")[0] 
data[ 'phone_prefix' ] 		= business.local_phone.split("-")[1]
data[ 'phone_suffix' ] 		= business.local_phone.split("-")[2]
data[ 'phone' ]			= data[ 'phone_prefix' ] #+ data[ 'phone_suffix' ]
data[ 'city' ]			= business.city
data[ 'state' ]			= business.state_name
data[ 'zip' ]			= business.zip
data[ 'location_name' ]		= business.address
data[ 'email' ]			= business.bings.first.email 
data[ 'contact_description' ]	= "Owner"
data[ 'nameFNL' ]		= business.contact_first_name + ' ' + business.contact_last_name
data[ 'linkdescription' ]	= "Homepage"
data
