data = {}
data[ 'username' ]		= business.primeplaces.first.username
data[ 'password' ]		= business.primeplaces.first.password
data[ 'fname' ]			= business.contact_first_name
data[ 'lname' ]			= business.contact_last_name
data[ 'fullname' ]		= data[ 'fname' ] + ' ' + data[ 'lname' ]
primey = Primeplace.where(:business_id => business.id).first
data[ 'category1' ]          = primey.primeplace_category.parent.name
data[ 'category2' ]          = primey.primeplace_category.name
data[ 'state_name' ]		= business.state_name
data[ 'state' ]			= business.state
data[ 'city' ]			= business.city
data[ 'business' ]		= business.business_name
data[ 'addressComb' ]		= business.address + "  " + business.address2
data[ 'address' ]		= business.address
data[ 'address2' ]		= business.address2
data[ 'zip' ]			= business.zip
data[ 'phone' ]			= business.local_phone
data[ 'areacode' ]		= business.local_phone.split("-")[0]
data[ 'exchange' ]		= business.local_phone.split("-")[1]
data[ 'last4' ]			= business.local_phone.split("-")[2]
data[ 'fax' ]			= business.fax_number
data[ 'email' ]			= business.bings.first.email
data[ 'website' ]		= business.company_website
data[ 'description' ]		= business.business_description
data[ 'tagline' ]		= business.category1 + " " + business.category2 + " " + business.category3
data[ 'image' ]			= "C:\\1.jpg"
data[ 'country' ]		= "United States"
data[ 'suburb' ]		= "None"
data[ 'tollfree' ]		= business.toll_free_phone
data[ 'birthday' ]		= business.contact_birthday
data[ 'birth1']			= business.contact_birthday.split("/")[0]
data[ 'birth2']			= business.contact_birthday.split("/")[1]
data[ 'birth3']			= business.contact_birthday.split("/")[2]
data
