data = {}
data[ 'email' ]			= business.bings.first.email
data[ 'preferred_city' ]	= 'kansas city'
data[ 'password' ]		= business.bings.first.password
data['category'] = 'community'
data['sub_category'] = 'artists'
data['sub_category2'] = ''
data['my_gender'] = business.contact_gender
data['partner_gender'] = 'Woman'
data['city'] = 'SF bay area'
data['nearest_city'] = '1' #need all the craigslist codes to real names
data['age'] = '24'
data['image_path'] = ""
data['location'] = '0' #need all the craigslist codes to real names
data['posting_title'] = 'Testing'
data['catCode']	= "c" #need all the craigslist codes to real names
data['subCode'] = "70" #need all the craigslist codes to real names
data['subCode2'] = '' #need all the craigslist codes to real names
data['posting_description'] = 'This is Test. This is Test. This is Test. This is Test. This is Test. This is Test. This is Test. This is Test. This is Test'
data
