data = {}
data[ 'email' ]	= business.bings.first.email
data[ 'password' ]	= Yahoo.make_password
data[ 'first_name' ] = business.contact_first_name
data[ 'last_name' ] = business.contact_last_name
data[ 'full_name' ] = data[ 'first_name' ] +' '+ data[ 'last_name' ]
data[ 'address' ] = business.address + ' ' + business.address2
data[ 'city' ] = business.city
data[ 'state' ] = business.state
data[ 'zip' ] = business.zip
data[ 'business' ] = business.business_name
data[ 'businessfixed' ] = data['business']
data[ 'business_category' ] = business.category1
data['location'] = data[ 'business' ] +', '+ data[ 'city' ]
data['country'] = 'United States of America'
data[ 'website'] = business.company_website
data[ 'business_description' ] = business.business_description
data[ 'phone' ] = business.local_phone
data[ 'fax' ] = business.fax_number
data
